### ISSUE TITLE
stddoc keeps hanging

### ISSUE THREAD

**Issue by clankill3r** [r-lyeh/stddoc.c#4]
I compiled stddoc.c using:

```
gcc -o stddoc stddoc.c
```

I tried to use it on stddoc.c but it keeps hanging:

<img width="616" alt="screen shot 2018-01-11 at 00 07 03" src="https://user-images.githubusercontent.com/738650/34800328-87897540-f663-11e7-8056-befb3b24c016.png">

Hope you can help, your project looks great.

**Comment by r-lyeh-archived** [comment]
Hello there,  thanks :) Try to use pipes instead (notice the less-than and greater-than symbols) 

<pre>./stddoc.c < stddoc.c > tes2.html</pre>

**Comment by clankill3r** [comment]
Ah cool, I will try.
I thought you mean them like replace `< source.file >` with the source file.

**Comment by r-lyeh-archived** [comment]
Yeah np. I've uploaded a new source that will prevent this issue hopefully :)

**Comment by clankill3r** [comment]
Good to hear that my mistakes make your product better :)
