### ISSUE TITLE
code blocks not looking correct

### ISSUE THREAD

**Issue by clankill3r** [r-lyeh/stddoc.c#5]
All blank lines are gone and the width doesn't wrap / scroll.
(Not sure if this is a markdeep, markdown or stddoc issue).

<img width="1075" alt="screen shot 2018-01-11 at 18 51 46" src="https://user-images.githubusercontent.com/738650/34840385-28dec534-f705-11e7-80ba-ce3eb3b2d5f9.png">

**Comment by clankill3r** [comment]
The blank lines is your part I just figured out.

**Comment by r-lyeh-archived** [comment]
That's a long line to quote tbh.
I think it would be better to have the TOC index on the left, and let the page content scroll freely to the right (that's the markdown apidoc.css stylesheet to fix afaik).
Also, ensure the blanks lines have a ending space after the 3 bars `/// ` to force a newline.

**Comment by clankill3r** [comment]
I know it's long :) Sometimes it has to be :)
I added this to the top to fix it:

`/// <style> .backtick { overflow-y: scroll; } </style>`

<img width="857" alt="screen shot 2018-01-12 at 03 21 36" src="https://user-images.githubusercontent.com/738650/34856842-c6045242-f747-11e7-8b60-ed6c09490705.png">

**Comment by r-lyeh-archived** [comment]
Very cool ty :D I've tweaked the generator to support an alternative fix. Btw, what is the issue with the blank lines then? I think I don't get the point.

**Comment by clankill3r** [comment]
The new lines where gone, but that is fixed with the space you mentioned.
