### ISSUE TITLE
feuture request, a way to fail the 'compiler'

### ISSUE THREAD

**Issue by clankill3r** [r-lyeh/stddoc.c#6]
Let's say I have a bunch of procedures, and above every procedure I make a comment so my procedures end up in the document:

```java
/// `static void find_blobs(Blob_Scanner_Context context)` <br>
public static void find_blobs(Blob_Scanner_Context context) {   
```

While working on my code I might change the parameters to:

```java
/// `static void find_blobs(Blob_Scanner_Context context)` <br>
public static void find_blobs(Blob_Scanner_Context context, float threshold) {
```

I really don't want to update documentation when working on code. But I also want to make the risk of my documentation being uncorrect as small as possbille.
Therefor I would really like something like:

```java
/// `static void find_blobs(Blob_Scanner_Context context)` <br>
/// !stddoc fail!
public static void find_blobs(Blob_Scanner_Context context, float threshold) {
```
And then when using `stddoc < my.code > out.html` it should not create the out.html but tell me the file name and line number instead.

**Comment by r-lyeh-archived** [comment]
I wont be able to support a full featured documentation generator (aka, lexer, parser, AST, etc...) in the near future. Also, that would mean starting to support each syntax differences per supported language.

I think the project is quite beauty in its minimalistic form atm, which does nothing when parsing. But, if I find a way to support this easily I will do it of course.

**Comment by clankill3r** [comment]
A lexer / parser / AST would kill the soul of this project.

I never program in C or anything where you have to allocate memory so this is probably pretty horrible but it works :)
(I'm waiting for JAI).

```C
/**/ if( fsm_S <= 2 && chr == '/' && !fsm_D && !fsm_H ) fsm_S++;
        else if( fsm_S == 3 && chr == ' ' && !fsm_D && !fsm_H ) fsm_S++;
        else if( fsm_D <= 2 && chr == '-' && !fsm_S && !fsm_H ) fsm_D++;
        else if( fsm_D == 3 && chr == ' ' && !fsm_S && !fsm_H ) fsm_D++;
        else if( fsm_H <= 2 && chr == '#' && !fsm_S && !fsm_D ) fsm_H++;
        else if( fsm_H == 3 && chr == ' ' && !fsm_S && !fsm_D ) fsm_H++;
        else if( (fsm_S == 3 || fsm_D == 3 || fsm_H == 3) && chr == '!')  {
            int str_len = 1024;
            char *error_msg = malloc(str_len * sizeof(char));
            int i = 0;
            while (1) {
                chr = getc(in);
                if( chr == '\r' || chr == '\n' ) break;
                error_msg[i] = chr;
                i++;
            }
            perror(error_msg);
        }
        else fsm_S = fsm_D = fsm_H = 0;
```

I use this in the documentation / source:

`///! Print this to the console `

<img width="585" alt="screen shot 2018-01-12 at 04 36 09" src="https://user-images.githubusercontent.com/738650/34858724-2e702ffe-f752-11e7-8bbb-e0828feb94a9.png">

I think something like this can be really nice.

It would be good to have a better syntax then `///!` cause it's to verbose.
It would be better if it stand out more, as in more characters but it should not be the ! character then cause then it will look like a note / tip / warning / error.

(Also the way I make the string is really unsafe with the fixed buffer...).

**Comment by clankill3r** [comment]
Seems I learn fast

```C
#pragma once
#include <stdio.h>
#include <stdlib.h>

static void stddoc( FILE *in, FILE *out ) {
    fprintf(out, "%s\n", "<meta charset='utf-8' emacsmode='-*- markdown -*-'>");
    fprintf(out, "%s\n", "<link rel='stylesheet' href='https://casual-effects.com/markdeep/latest/apidoc.css?'>");

    int line = 1;

    for( int fsm_S = 0, fsm_D = 0, fsm_H = 0; !feof(in); ) {
        int chr = getc(in);
        if( fsm_S > 3 || fsm_D > 3 || fsm_H > 3 ) {
            putc(chr, out);
            if( chr != '\r' && chr != '\n' ) continue;
        }
        /**/ if( fsm_S <= 2 && chr == '/' && !fsm_D && !fsm_H ) fsm_S++;
        else if( fsm_S == 3 && chr == ' ' && !fsm_D && !fsm_H ) fsm_S++;
        else if( fsm_D <= 2 && chr == '-' && !fsm_S && !fsm_H ) fsm_D++;
        else if( fsm_D == 3 && chr == ' ' && !fsm_S && !fsm_H ) fsm_D++;
        else if( fsm_H <= 2 && chr == '#' && !fsm_S && !fsm_D ) fsm_H++;
        else if( fsm_H == 3 && chr == ' ' && !fsm_S && !fsm_D ) fsm_H++;
        else if( (fsm_S == 3 || fsm_D == 3 || fsm_H == 3) && chr == '!')  {
            fprintf(stderr, "%i\t", line);
            while (!feof(in)) {
                chr = getc(in);
                if( chr == '\r' || chr == '\n' ) break;
                fprintf(stderr, "%c", chr);
            }
            fprintf(stderr, "\n");
        }
        else {
            fsm_S = fsm_D = fsm_H = 0;
            line++;
        }
    }

    fprintf(out, "%s\n", "<script>markdeepOptions={tocStyle:'medium'};</script>"); // tocStyle{auto, none, short, medium, long}
    fprintf(out, "%s\n", "<!-- Markdeep: --><script src='https://casual-effects.com/markdeep/latest/markdeep.min.js?'></script>");
}
```

<img width="569" alt="screen shot 2018-01-12 at 04 51 47" src="https://user-images.githubusercontent.com/738650/34859072-560b07ee-f754-11e7-8f99-967b949b26d6.png">

No more allocation problems.
And I added a line number which is correct :)

Only thing left to do is a better syntax for the error.
I hope you like it and will integrate it in some way.

**Comment by r-lyeh-archived** [comment]
Ahhh, you meant that you want to force a "doc assert" when documenting, right?! So you put a mark and expect that the generator will fail any other day you launch the docgen process, right? Sounds neat.

**Comment by clankill3r** [comment]
Yeah it either fails or gives a warning in the console yo remind you of something. Could be optional.

**Comment by r-lyeh** [comment]
I have created a gist here. Let me know if it addresses the feature:

https://gist.github.com/r-lyeh/1c539ed9a1bd9fee7cbb50da71fb3e4d

```c
///# bla bla
///! this line will invoke a comment
```

**Comment by r-lyeh** [comment]
Also, added a check to support markdeep comments with or without that ending blank space.
Also, check #7.

**Comment by clankill3r** [comment]
I had a brief look but quite a lot is changed compared to how it was.
I'm only tired af, and won't have time to look better at it next week, but
i'm sure you manage fine :) .

2018-01-15 15:27 GMT+01:00 r-lyeh <notifications@github.com>:
