### ISSUE TITLE
literate programming?

### ISSUE THREAD

**Issue by meshula** [r-lyeh/stddoc.c#7]
Short of quoting code in comments, is there a syntax to enable literate programming?

Something like

    /// Bubble sort, sometimes referred to as sinking sort, is a simple sorting 
    /// algorithm that repeatedly steps through the list to be sorted, compares 
    /// each pair of adjacent items and swaps them if they are in the wrong order. 
    /// ![Figure [bubblesort]: Bubble sort in operation ](https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Bubblesort-edited-color.svg/440px-Bubblesort-edited-color.svg.png border="1")
    /// ~~~~~~~~~~~~~~~~~~~~!C
    void bubbleSort(int arr[], int n)
    {
       int i, j;
       for (i = 0; i < n-1; i++)       
           // Last i elements are already in place   
           for (j = 0; j < n-i-1; j++) 
               if (arr[j] > arr[j+1])
                  swap(&arr[j], &arr[j+1]);
    }
    /// ~~~~~~~~~~~~~~~~~~~~!C

I added a bang to suggest that following code block should appear in the generated doc without having to duplicate it with /// in front of every line.

**Comment by r-lyeh** [comment]
That would be cool. I will think about adding a comment extension that allows quoting directly not only for a single line quote but also for a code block. The only problem to figure out is choosing the syntax markers carefully so they do not interfere with markdeep syntax, plus the other 60 language syntaxes.

**Comment by r-lyeh** [comment]
I've created a gist here. Let me know if that helps addressing the feature:

https://gist.github.com/r-lyeh/1c539ed9a1bd9fee7cbb50da71fb3e4d

You can either do a generic quote:
```c
///<
int main();
///>
```

or specify a language when quoting instead:
```c
///<C++
int main();
///>
```

**Comment by r-lyeh** [comment]
Also, closing the quote is optional once a new stddoc comment is found.
There is a better sample in [stdstring.h header](https://github.com/r-lyeh/stdstring.h).

**Comment by meshula** [comment]
That's exactly what I was looking for! Trying it out :)

**Comment by meshula** [comment]
That's exactly what I was hoping for. I'm writing a little coding tutorial, and I love that the article is easy to read, and the code that generates the article compiles and runs. Thanks for building stddoc!

**Comment by r-lyeh** [comment]
Cool,  glad to help.  Kudos to McGuire!  :)

**Comment by meshula** [comment]
There's a little funkiness at the end of the file. In order to prevent the last tag from turning to goo (///> prints ~~~>, I had to add a random line of code.

    /// some explanations
    ///<C++
    int main(int argc, char* argv[])
    {
    	ApplicationContext context;
    	std::vector<std::thread> jobs;
    	jobs.emplace_back(std::thread([&context]() { state_engine(context); }));
    	jobs.emplace_back(std::thread([&context]() { render_engine(context); }));
    	jobs.emplace_back(std::thread([&context]() { ui_engine(context); }));
    	for (auto& j : jobs)
    		if (j.joinable())
    			j.join();
    	return 0;
    }
    ///>
    void foo() {} // trick stddoc into terminating the file nicely

**Comment by r-lyeh** [comment]
Updated the gist right now. Hope it works now! :)

**Comment by meshula** [comment]
The end of file handling is improved, but I still need at least this - 

    ///>
    ;

at the end of the file. If I omit the ///> the last block doesn't format, and omitting the ; results in the last line reading as ~~~>

**Comment by meshula** [comment]
Yep! All good! Thanks!

**Comment by meshula** [comment]
I'm back ..... heh ;)

Let's say I was writing an article about application context, and my thread handling is irrelevant to the discussion. It would be nice to have an elision.

    /// some explanations
    ///<C++
    int main(int argc, char* argv[])
    {
    	ApplicationContext context;
        ///...>C++
        // uninteresting details
    	std::vector<std::thread> jobs;
    	jobs.emplace_back(std::thread([&context]() { state_engine(context); }));
    	jobs.emplace_back(std::thread([&context]() { render_engine(context); }));
    	jobs.emplace_back(std::thread([&context]() { ui_engine(context); }));
    	for (auto& j : jobs)
    		if (j.joinable())
    			j.join();
        ///...>
    	return 0;
    }
    ///>

The idea would be that in the generated doc, the elided portion is replaced with an ellipsis (or an accordion, except markdeep doesn't have accordions I think).

**Comment by meshula** [comment]
The snippet below doesn't work -

    /// Looks like iostreams freak out the parser
    ///<C++
    Detail()
    {
        std::cout << "OpenGL Version: " << version <<std::endl;
    }
    ///>

Update:
Not iostreams per se, << is an instruction to markdeep. So when it hits the <<s with no space, markdeep thinks it's in the middle of a strikeout command it messes up everything.  So it seems like this is more of a markdeep issue.

**Comment by r-lyeh** [comment]
Good catch. It's actually the `<<std::endl` part what scares markdeep. Inserting a blank space there solves the rendering.

Btw, I have updated the gist to support nested code blocks, which will be more or less the base for an upcoming embedded accordion javascript snippet.

You could do theorically up to 255 nested comments like:

```C++
/// some explanations
///<C++
int main(int argc, char* argv[])
{
        ApplicationContext context;
    ///<
        std::vector<std::thread> jobs;
        jobs.emplace_back(std::thread([&context]() { state_engine(context); }));
        jobs.emplace_back(std::thread([&context]() { render_engine(context); }));
        jobs.emplace_back(std::thread([&context]() { ui_engine(context); }));
        for (auto& j : jobs)
                if (j.joinable())
                        j.join();
    ///>
        return 0;
}
///>
/// bla bla...
```

**Comment by r-lyeh** [comment]
Mailed @Morgan3d about this issue as well
