### ISSUE TITLE
Hi just to inform you

### ISSUE THREAD

**Issue by 22karthik** [r-lyeh/stddoc.c#8]
Hi @r-lyeh 
You just replied to me yesterday.I dont have that good knowledge in programming.Can you just let me if have any info on the syntax for public key in elliptic curve diffie hellmann key exchange.

I guess Iam making mistake in the syntax for manual key insertion instead of algorithm generating one for me.

I didn't anyother way to communicative with you other than opening this issue.Thank you

**Comment by pburger24** [comment]
hi this is embarassing event from your past. can u close it?

**Comment by r-lyeh** [comment]
Closing. EDCH does not belong to this repo.
